name: Go CD

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Notice
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        initial_comment: '${{ github.commit }} CD start'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/Documents/Backend-GAuth-server
          git pull
          docker build . -t go-auth-server
          docker stop Go-Auth-Server
          docker rm Go-Auth-Server
          docker image prune -f
          docker run -d --name Go-Auth-Server -p 5080:8080 go-auth-server
    
    - name: Notice
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.